# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-20 04:57
from __future__ import unicode_literals

from django.db import migrations, models
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20181019_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='locality',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contact',
            field=models.TextField(max_length=1000),
        ),
    ]
